/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        double[] data = { 10.0, 20.0, 30.0, 40.0, 50.0 };

       
        System.out.println("Obliczanie statystyk dla danych:");
        Compute.calculateStatistics(data);
    }
}
